ktor:
    application:
        modules:
            - com.ducks.ApplicationKt.module
    deployment:
        port: 8080
    database:
      password: "$DB_PASS"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "ducks-audience"
  issuer: "http://localhost"
  realm: "ducks realm"
  secret: "$SECRET"
